on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 9

      - run: pnpm install
      - run: pnpm build

      - name: push to ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: greegko.com
          username: u584298536
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./compress-clipboard-image/
